apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefileserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubefileserver
  template:
    metadata:
      labels:
        app: kubefileserver
    spec:
      volumes:
      - name: files
        persistentVolumeClaim:
          claimName: pvczg
      containers:
      - name: kubefileserver
        image: gcr.io/zoneguardian-187817/kubefileserver
        volumeMounts:
        - name: files
          mountPath: /usr/src/app/files
        ports:
        - containerPort: 3000