apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefileserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubefileserver
  template:
    metadata:
      labels:
        app: kubefileserver
    spec:
      volumes:
      - name: files
        persistentVolumeClaim:
          claimName: pvczg
      containers:
      - name: kubefileserver
        image: gh3s/kubefileserver
        volumeMounts:
        - name: files
          mountPath: /usr/src/app/files
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: balancer-service
spec:
  type: LoadBalancer
  ports:
  - port: 8555
    targetPort: 3000
    protocol: TCP
  selector:
    app: kubefileserver