apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvzg
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/usr/src/app/files"