kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: pvczg
spec:
    accessModes:
      - ReadWriteOnce
    storageClassName: standard
    resources:
        requests:
            storage: 40Gi